import React from 'react'
import EventRow from './EventRow'

export default function Events(){
    const events = {
        Radiant : "Hola SCTians✨\nThe IEEE Student Branch of SCT is excited to announce \" RADIANT⚔️\" an exclusive Valorant tournament for all SCTians. In this tournament, participants will get the opportunity to showcase their skills and compete with their peers in the world of online gaming.\nSo, SCTians, it's time to rise to the challenge and take on the competition in Challengers. Register now and get ready to battle it out in the world of Valorant!\nRegistrations are absolutely Free ❗❗❗\n🔰General Guidelines:\n1. Eligibility: Only SCTians are eligible\n2. Registration: Team registration with 5 members from any class. (Mixed teams allowed.)\n3. Game Format: Knockout format\n4. Game Settings: Default settings of the game \n5. Fair Play: No cheating or unfair play \n6. Reporting: Scores reported immediately after the match \n 7. Conduct: Respectful and sportsmanlike conduct required\n 8. Organizers' Decision: Final and binding\n10. No Smurf accounts allowed\n11. Registration is accepted till 2pm on 16th April. \nNote: Preliminary matchmaking will be done only based on the player rankings of each team\nFor any query contact :\nPranav Baburajan : 7994329200\nAkshai Sathya : 9947244269",
        Xmarks :"Are you ready to put your treasure-hunting skills to the test? If so, then you don't want to miss the X Marks, the treasure hunt💰, one of the coolest events of Resurgence 2.0 organized by IEEE SCT SB ✨.\nIn this exciting game, teams of four will compete against each other to solve a series of clues that will lead them to the next challenge. But it's not just about solving the clues - teams will also be given tasks to complete along the way, testing their skills and creativity.\nBut wait, there's a catch 👀!\n📌 Only two teams can participate from each class, and each team must have four members.\nSo, gather your friends and make sure you're registered early to secure your spot.\n📌Also, please note that if more than two teams register from a class, only the first two teams will be considered.\n📌 All registered participants must be present on the day of the event.\nMode : offline \nVenue : SCT Campus \n*Date of event: 19 April 2023* \nLast date to register: 17  April 2023 .\nSo, get ready to put your detective skills to the test and compete for the ultimate prize in the X Marks treasure hunt!\nContact:\nPriya Piyuse:6282528942\nNandini : 6282666134",
        Innovation :"As part of Resurgence 2.0, IEEE SCT SB brings you Innovation Conclave, an Idea hackathon for you to put your best foot forward and present your creative thoughts and ideas which can better live itself.💡\nTheme: AI for social good\nThe participants should provide a brief explanation of the problem and present their abstract for a solution. \nRules & Regulations:\n🛑A team can consist of 2-3 members from the same class. \n🛑The technical aspects and the technologies used will be checked for factual correctness.\n🛑Abstract should provide a clear picture of the solution. \n🛑Participants must present their idea with a presentation. \n🛑Originality of ideas is highly appreciated.\n🛑Decisions taken by the Judges are final.  \n🛑Judging will be based on the topic AI for Social Good, innovativeness, and feasibility of the presented idea.\nFinal date of submission:- 17/04/2023\nRegister now and stun the world with your imaginative solutions. 💫\nFor queries:\n📱Praful George: +91 97478 36567\n📱 Fahad: +91 94950 30000",
        Consumer :"\“Don’t find customers for your products, find products for your customers.” – Seth Godin.\n✨Greetings from IEEE SCT SB!\nWe as a part of Resurgence, technical- literacy  fest organized by SCT SB.\nWe are opening the registration for the sell me the product event Consumer Carousal✨\nThe rules are as follows:\n📌 Competition will be held in Google Meet. \n📌 Participants will be given basic details of a product, and they must talk and market it in such a way that the judges get convinced to buy it. \n📌 Make use of your creativity, speaking, and marketing skills. \n📌 Participants will be allocated 5 minutes for both preparing and presenting and marketing the given product. \n📌 Participants must answer the queries of the judges, if any. \n📌 Language of medium: English or Malayalam.\n📌 The decision of the judging committee will be final. \ndate: 18 April 2023!✨\nRegister now : bit.ly/ConsumerCarousal\nLet's get going!!\nAny queries? Contact \nGayathri- +919895614516\n\nSreerag -+919995366005",
        QQQ :"_\"Words are, in my not-so-humble opinion, our most inexhaustible source of magic.\"-Albus Dumbledore_\nHey peeps! Do you think you have what it takes to speak eloquently and concisely under pressure in a quick minute🌚? Even if you do not, don't worry great speakers are not born they learn with experience ✨🙌.\nIEEE SCT SB presents,\nQuick Quip Quell\n-A Just-a-Minute Competition as part of Resurgence 2.0\nSo get ready to test your speaking skills and quick thinking🤓🧠 and lead your class to victory💪\n1. This is a just a-minute competition as the name suggests participants have to speak on the topic given in 1 minute. Any additional time taken will be charged with a penalty in score \n2. The topic for the participant will be given 1 minute prior to the turn of the participant\n3. The language mode should be strictly English \n4. Participants should ensure an active internet connection and have to stay online during the duration of the competition\n5. The theme for topics can be technical and non-technical.\n🗓️Date:16th April,2023\n⏰Time:7pm\n💻Platform: Gmeet\nContact\nVishnupriya: 8301927462\nSidharth: 90743 90983",
        Picture : "\"You don\'t take a photograph, you make it\" - Ansel Adams.\nPhotography, the art of capturing perfect moments, in perfect snaps.\nA Talent that sets people apart from the rest, through a single click.\nAnd what better moment to capture the best of your talents than in this spring of resurgence?\nRESURGENCE 2.0 brings to you PICTURE PERFECT,\nThe opportunity for you to show off your Togging expertise.\nBut how will any fun competition be cool without some rules?\nSo here are some quick points for you to remember:\n1. There is no theme, may your imagination guide your lens to it\'s best\n2. A contestant can upload a maximum of two files from a single Gmail account\n3. There should be no Plagiarism of any kind\n4. Self portraits and Model photos are not allowed\n5. Both Camera and Mobile Photographs are permitted.\nFinal date of submission: 18th April, 2023\nFor more details, contact\nAbhinand : 7592068056\nNiranjana : +91 73063 69482",
        Elastico : "Hey, what's up? SCTians✨️\nThe IEEE SCT SB is proud to announce the launch of \"Elastico\",an exclusive E-football tournament for all the SCTians as a part of Resurgence 2.0 ⚽\nSo, gear up, SCTians, and get ready to showcase your gaming skills in Elastico. Let's kick off this tournament and show the world what we're made of!⚔️\nRegistrations are absolutely free❗❗\n⚠️ General guidelines:\n📌Anyone from any Class can participate ( Only SCT ians).\n📌Will be conducted as a knockout tournament with no squad restrictions.\n📌Match time should be set to 8 minutes.\n📌Extra time and penalty should be turned on.\n📌Any sort of hack usage or cheating will result in direct disqualification.\n📌Decisions made by coordinators will be final.\n📌 Competition will commence from 16/4/2023\n📌Final date of registration : 16/4/2023, 1 pm.\nFor any query -\nAkshai Sathya: 9947244269\nSreedhar : 8075496634",
        Meme :"\"To succeed in life, you need three things: a wishbone, a backbone, and a funny bone\"\nReba McEntire\nHola SCTians!!\nAre you searching for an opportunity to show your shades of humor and make the room laugh?🤔\nThen here comes your time!!!😌\nIEEE SCT SB presents an online meme making competition ⚡\n\"MEME INTO\" ⚡ as a part of  Resurgence 2.0💫💫Topic: Anything related to SCT🏫\n( Eg:- Attendance criteria, Expectation vs Reality in SCT)\nInstructions : \n📌 Fill the Google form and attach your work along with it.\n📌 This is an individual event.\n 📌 One entry per person\n📌  Your entries must be solely yours and not copied from any other sources.\n📌 Decision of the judges will be final.\n 🗓️Deadline :18/04/2023 :11.59 pm\nFor any doubts, contact:\nHelen: +91 81118 03592\n📱Devabhadra : +91 9497813650\nSo why wait? fill out the form to unveil your inner meme god!👼🏻✨",
        Planet :"\"Let's go invent tomorrow instead of worrying about what happened yesterday \"\n- Steve Jobs\nIEEE SCT SB as part of Resurgence 2.0 presents\n🌍 Planet Pitch\n🎓Show us your ideas on how to make our world a better place! Submit your abstracts on solutions to any one of the two topics below, \n👣 Small steps, big impact\n~  Reducing Carbon Footprints for Sustaining Future Generations\n🌱 Sustainable Agriculture and Unsustainable Actions\n~ Zero Poverty and Hunger, Responsible Consumption and Production\nGuidelines: \n1. Word count should be around 250-300 \n2. Any attempt at plagiarism will result in disqualification\n 3. No entries will be entertained after the deadline\n 4. The decision taken by the judges will be final\n 5. In case of similar ideas, earlier submission will be considered \n6. Entries will be judged on innovation, feasibility, marketability, relevance to theme and presentation. \nNote: Please submit your entries in pdf form\nTeam size: 1-4 members\n🛑 Deadline: 18/04/2023\nIn case of queries contact\n📱Parvati: wa.me/+91 9072372049\n📱Krishna: wa.me/+91 8075879679",
        TheArt :"Resurgence 2.0 brings you The Art of Argument, a debate competition to see who can win the war of words and ideas. Do you have a fiery tongue to argue, or a silver tongue to sway your opponents? Do you have a will of steel, or do you bend you words? Register now and find out. 🗣️\n🗓️ Last Date to Register: 17th April 2023\nGuidelines:\n🛑Teams of 2-3 members\n🛑For or against assigned by coin toss.\n🛑5-minute break for preparation.\n🛑Opening statement, rebuttal, and closing statement time limits: typically 5-7 minutes.\n🛑Opening statement: present argument and evidence.\nRebuttal: respond to opposing team's arguments.\nClosing statement: summarize argument and restate position.\n🛑Judging based on argument, evidence, presentation skills, and overall performance.\n*Date of Event: 18th April 2023*\nFor queries:\nSufail S:- +91 77366 64918.\nHari Krishna k:-+91 80788 60696.",
        Design :"\"Design Duel : Embracing Our Differences✨\"\nDo you have a passion for design 🎨? Do you believe in celebrating diversity and embracing our differences? Then participate in our poster designing competition as a part of RESURGENCE 2.0  conducted by IEEE SCT SB!!\nSubmit your original poster design on the theme of \"Embracing Our Differences\" \nRules and Regulations:\n📍The size of the poster should be 1080 x 1080 px.\n📍Each participant can submit only one poster.\n📍Any plagiarism found will lead to disqualification.\n📍Posters to be made using any design apps (Canva, Photoshop, Figma etc.\n📍Make sure to stick to the deadline (18/04/2023). \nJoin us in celebrating diversity through the power of design🎉.\nFor any queries, contact\nNevin: 9074910964 \nNandana: 9400861133",
    }
    return(
        <div className='p-[4vw]' id='events'>
            <h1 className='heading'>Events</h1>
            <div className='flex gap-10 relative rowContainer'>
                <div className='flex flex-col gap-5 w-full'>
                    <EventRow name="Radiant - Valorant" poster="/valo.jpeg" link="https://min.lc/Radiant" content={events.Radiant}/>
                    <EventRow name="X marks - Treasure Hunt" poster="/Xmarks.jpeg" link="https://bit.ly/3mue09C" content={events.Xmarks}/>
                    <EventRow name="Innovation Conclave - Idea Hackathon" poster="/innovation.jpeg" link="http://bit.ly/Innovation_conclave" content={events.Innovation}/>
                    <EventRow name="Consumer Carousal - Sell me a product" poster="/Consumer.jpeg" link="http://bit.ly/ConsumerCarousal" content={events.Consumer}/>
                    <EventRow name="Quick Quip Quell - Just A Minute" poster="/qqq.jpeg" link="http://bit.ly/ResurgenceJAM" content={events.QQQ}/>
                    <EventRow name="Picture Perfect - Photography" poster="/picture.jpeg" link="https://bit.ly/picturePerfect" content={events.Picture}/>
                </div>
                <div className='flex flex-col gap-5 w-full'>
                    <EventRow name="Elastico - EFootball" poster="/Elastico.jpeg" link="https://bit.ly/ELastico" content={events.Elastico}/>
                    <EventRow name="Meme Into - Meme making" poster="/meme.jpeg" link="https://bit.ly/memeinto" content={events.Meme}/>
                    <EventRow name="Planet Pitch - Idea Hackathon" poster="/planet.jpeg" link="https://bit.ly/Planetpitch" content={events.Planet}/>
                    <EventRow name="The Art of Argument - Debate" poster="/the art of.jpeg" link="http://bit.ly/4073WRM" content={events.TheArt}/>
                    <EventRow name="Design Duel - Poster Design" poster="/design.jpeg" link="https://bit.ly/PosterDesigningCompetetion" content={events.Design}/>
                </div>
            </div>
            
        </div>
    )
}